name: pytest
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Run a git clone
        uses: actions/checkout@v3

      - name: install python
        run: pip install pytest

      - name: run pytest
        run: pytest
