name: pytest
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Run a git clone
        run: |
          git clone https://github.com/boscobao/github-action1.git 
          cd github-action1

      - name: install python
        run: pip install pytest

      - name: run pytest
        run: pytest
